services:
  _defaults:
    public: true

  contao_bootstrap.core.config_subscriber:
    class: ContaoBootstrap\Core\Listener\ConfigSubscriber
    arguments:
      - '@database_connection'
      - '@contao_bootstrap.config'
    tags:
      - { name: kernel.event_subscriber }

  contao_bootstrap.core.listener.parse_template:
    class: ContaoBootstrap\Core\Listener\TemplateParseListener
    arguments:
      - '@contao_bootstrap.view.template.pre_render_filter'
      - '@contao_bootstrap.view.template.post_render_filter'

  contao_bootstrap.core.listener.hook_listener:
    class: ContaoBootstrap\Core\Listener\HookListener
    arguments:
      - '@event_dispatcher'
      - '@contao_bootstrap.environment'

  contao_bootstrap.core.listener.content_dca:
    class: ContaoBootstrap\Core\Listener\Dca\ContentDcaListener
    arguments:
      - '@contao_bootstrap.environment'

  contao_bootstrap.core.listener.layout_dca:
    class: ContaoBootstrap\Core\Listener\Dca\LayoutDcaListener
    arguments:
      - '@contao_bootstrap.environment'

  contao_bootstrap.core.listener.module_dca:
    class: ContaoBootstrap\Core\Listener\Dca\ModuleDcaListener
